---
- name: "update apt cache"
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: "install handy packages"
  apt: pkg={{ item }} state=latest
  become: yes
  with_items: "{{ common_packages }}"

- name: "installing python deps"
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  become: yes
  with_items: "{{ pip_packages }}"